In [190]:
import numpy as np
import pandas as pd
import re

pd.options.display.max_rows = 50
pd.options.display.max_columns = 100

In [197]:
df = pd.read_csv('test.csv')
batting_2008 = pd.read_csv('batting_2008.csv')
batting_2009 = pd.read_csv('batting_2009.csv')
batting_2010 = pd.read_csv('batting_2010.csv')
batting_2011 = pd.read_csv('batting_2011.csv')
batting_2012 = pd.read_csv('batting_2012.csv')
batting_2013 = pd.read_csv('batting_2013.csv')
batting_2014 = pd.read_csv('batting_2014.csv')
batting_2015 = pd.read_csv('batting_2015.csv')

pitching_2008 = pd.read_csv('pitching_2008.csv')
pitching_2009 = pd.read_csv('pitching_2009.csv')
pitching_2010 = pd.read_csv('pitching_2010.csv')
pitching_2011 = pd.read_csv('pitching_2011.csv')
pitching_2012 = pd.read_csv('pitching_2012.csv')
pitching_2013 = pd.read_csv('pitching_2013.csv')
pitching_2014 = pd.read_csv('pitching_2014.csv')
pitching_2015 = pd.read_csv('pitching_2015.csv')

player_contracts = pd.read_csv('player_contracts.csv')
bdf = pd.read_csv('batter_contracts.csv')
pdf = pd.read_csv('pitcher_contracts.csv')

In [198]:
data = df[['Rk','Name','Age','Tm','Lg','G','PA','AB','R','H','2B','3B','HR','RBI','SB','CS','BB','SO','BA','OBP','SLG','OPS','OPS+','TB','GDP','HBP','SH','SF','IBB','Pos Summary']]

In [199]:
batting_2008.drop_duplicates(subset=['Name'], keep='first', inplace = True)
batting_2008['Name'] = batting_2008['Name'].str.replace('*', '')
batting_2008['year'] = '2008'

batting_2009.drop_duplicates(subset=['Name'], keep='first', inplace = True)
batting_2009['Name'] = batting_2009['Name'].str.replace('*', '')
batting_2009['year'] = '2009'

batting_2010.drop_duplicates(subset=['Name'], keep='first', inplace = True)
batting_2010['Name'] = batting_2010['Name'].str.replace('*', '')
batting_2010['year'] = '2010'

batting_2011.drop_duplicates(subset=['Name'], keep='first', inplace = True)
batting_2011['Name'] = batting_2011['Name'].str.replace('*', '')
batting_2011['year'] = '2011'

batting_2012.drop_duplicates(subset=['Name'], keep='first', inplace = True)
batting_2012['Name'] = batting_2012['Name'].str.replace('*', '')
batting_2012['year'] = '2012'

batting_2013.drop_duplicates(subset=['Name'], keep='first', inplace = True)
batting_2013['Name'] = batting_2013['Name'].str.replace('*', '')
batting_2013['year'] = '2013'

batting_2014.drop_duplicates(subset=['Name'], keep='first', inplace = True)
batting_2014['Name'] = batting_2014['Name'].str.replace('*', '')
batting_2014['year'] = '2014'

batting_2015.drop_duplicates(subset=['Name'], keep='first', inplace = True)
batting_2015['Name'] = batting_2015['Name'].str.replace('*', '')
batting_2015['year'] = '2015'

pitching_2008.drop_duplicates(subset=['Name'], keep='first', inplace = True)
pitching_2008['Name'] = pitching_2008['Name'].str.replace('*', '')
pitching_2008['year'] = '2008'

pitching_2009.drop_duplicates(subset=['Name'], keep='first', inplace = True)
pitching_2009['Name'] = pitching_2009['Name'].str.replace('*', '')
pitching_2009['year'] = '2009'

pitching_2010.drop_duplicates(subset=['Name'], keep='first', inplace = True)
pitching_2010['Name'] = pitching_2010['Name'].str.replace('*', '')
pitching_2010['year'] = '2010'

pitching_2011.drop_duplicates(subset=['Name'], keep='first', inplace = True)
pitching_2011['Name'] = pitching_2011['Name'].str.replace('*', '')
pitching_2011['year'] = '2011'

pitching_2012.drop_duplicates(subset=['Name'], keep='first', inplace = True)
pitching_2012['Name'] = pitching_2012['Name'].str.replace('*', '')
pitching_2012['year'] = '2012'

pitching_2013.drop_duplicates(subset=['Name'], keep='first', inplace = True)
pitching_2013['Name'] = pitching_2013['Name'].str.replace('*', '')
pitching_2013['year'] = '2013'

pitching_2014.drop_duplicates(subset=['Name'], keep='first', inplace = True)
pitching_2014['Name'] = pitching_2014['Name'].str.replace('*', '')
pitching_2014['year'] = '2014'

pitching_2015.drop_duplicates(subset=['Name'], keep='first', inplace = True)
pitching_2015['Name'] = pitching_2015['Name'].str.replace('*', '')
pitching_2015['year'] = '2015'

batting_temp_df = [batting_2008, batting_2009, batting_2010, batting_2011, batting_2012, batting_2013, batting_2014, batting_2015]
batting = pd.concat(batting_temp_df, keys = ['a','b','c','d','e','f','g','h'])
batting['year'] = batting['year'].astype('int')

pitching_temp_df = [pitching_2008, pitching_2009, pitching_2010, pitching_2011, pitching_2012, pitching_2013, pitching_2014, pitching_2015]
pitching = pd.concat(pitching_temp_df, keys = ['a','b','c','d','e','f','g','h'])
pitching['year'] = pitching['year'].astype('int')

batting

            Rk                 Name   Age   Tm   Lg    G   PA   AB    R    H  \
a 0        1.0        David Aardsma  26.0  BOS   AL   47    1    1    0    0
  1        2.0   Reggie Abercrombie  27.0  HOU   NL   34   60   55   10   17
  2        3.0          Bobby Abreu  34.0  NYY   AL  156  684  609  100  180
  3        4.0       Jeremy Accardo  26.0  TOR   AL   16    0    0    0    0
  4        5.0       Alfredo Aceves  25.0  NYY   AL    6    0    0    0    0
  5        6.0         Manny Acosta  27.0  ATL   NL   46    5    5    0    0
  6        7.0           Mike Adams  29.0  SDP   NL   54    2    2    0    0
  7        8.0        Nick Adenhart  21.0  LAA   AL    3    0    0    0    0
  8        9.0           Jon Adkins  30.0  CIN   NL    4    0    0    0    0
  9       10.0       Jeremy Affeldt  29.0  CIN   NL   74    1    1    0    0
  10      11.0         Chris Aguila  29.0  NYM   NL    8   15   12    0    2
  11      12.0  Jonathan Albaladejo  25.0  NYY   AL    7    0    0    0    0
  12      13.0          Matt Albers  25.0  BAL   AL   28    0    0    0    0
  13      14.0      Eliezer Alfonzo  29.0  SFG   NL    5   11   11    0    1
  14      15.0          Moises Alou  41.0  NYM   NL   15   54   49    4   17
  15      16.0          Chip Ambres  28.0  SDP   NL   24   48   41    3    8
  16      17.0      Alfredo Amezaga  30.0  FLA   NL  125  337  311   41   82
  17      18.0       Brian Anderson  26.0  CHW   AL  109  193  181   24   42
  18      19.0      Garret Anderson  36.0  LAA   AL  145  593  557   66  163
  19      20.0        Josh Anderson  25.0  ATL   NL   40  146  136   21   40
  20      21.0      Marlon Anderson  34.0  NYM   NL   87  151  138   16   29
  21      22.0        Robert Andino  24.0  FLA   NL   44   68   63    7   13
  22      23.0          Rick Ankiel  28.0  STL   NL  120  463  413   65  109
  23      24.0       Matt Antonelli  23.0  SDP   NL   21   65   57    6   11
  24      25.0          Greg Aquino  30.0  BAL   AL    9    0    0    0    0
...        ...                  ...   ...  ...  ...  ...  ...  ...  ...  ...
h 1589  1590.0  Asher Wojciechowski  26.0  HOU   AL    5    0    0    0    0
  1590  1591.0           Randy Wolf  38.0  DET   AL    8    0    0    0    0
  1591  1592.0          Kolten Wong  24.0  STL   NL  150  613  557   71  146
  1592  1593.0            Alex Wood  24.0  TOT   NL   32   67   55    2    9
  1595  1596.0          Travis Wood  28.0  CHC   NL   60   32   30    0    3
  1596  1597.0           Rob Wooten  29.0  MIL   NL    4    1    1    0    0
  1597  1598.0         Vance Worley  27.0  PIT   NL   24   18   17    1    3
  1598  1599.0         David Wright  32.0  NYM   NL   38  174  152   24   44
  1599  1600.0          Mike Wright  25.0  BAL   AL   12    3    2    0    1
  1600  1601.0        Steven Wright  30.0  BOS   AL   16    2    1    0    0
  1601  1602.0        Wesley Wright  30.0  TOT   AL   11    0    0    0    0
  1604  1605.0          Kirby Yates  28.0  TBR   AL   20    0    0    0    0
  1605  1606.0     Christian Yelich  23.0  MIA   NL  126  525  476   63  143
  1606  1607.0          Rafael Ynoa  27.0  COL   NL   72  131  127   14   33
  1607  1608.0          Chris Young  31.0  NYY   AL  140  356  318   53   80
  1609  1610.0         Delmon Young  29.0  BAL   AL   52  180  174   20   47
  1610  1611.0           Eric Young  30.0  TOT   NL   53   94   85   16   13
  1613  1614.0         Brad Ziegler  35.0  ARI   NL   66    0    0    0    0
  1614  1615.0       Ryan Zimmerman  30.0  WSN   NL   95  390  346   43   86
  1615  1616.0    Jordan Zimmermann  29.0  WSN   NL   33   69   63    4   10
  1616  1617.0           Barry Zito  37.0  OAK   AL    3    0    0    0    0
  1617  1618.0          Ben Zobrist  34.0  TOT   AL  126  535  467   76  129
  1620  1621.0          Mike Zunino  24.0  SEA   AL  112  386  350   28   61
  1621  1622.0            Tony Zych  24.0  SEA   AL   13    0    0    0    0
  1622     NaN     LgAvg per 600 PA   NaN  NaN  NaN  234  600  541   67  137

        2B  3B  HR  RBI  SB  CS  BB   SO     BA    OBP    SLG    OPS   OPS+  \
a 0      0   0   0    0   0   0   0    1  0.000  0.000  0.000  0.000 -100.0
  1      5   0   2    5   5   2   1   23  0.309  0.339  0.509  0.848  122.0
  2     39   4  20  100  22  11  73  109  0.296  0.371  0.471  0.843  120.0
  3      0   0   0    0   0   0   0    0    NaN    NaN    NaN    NaN    NaN
  4      0   0   0    0   0   0   0    0    NaN    NaN    NaN    NaN    NaN
  5      0   0   0    0   0   0   0    3  0.000  0.000  0.000  0.000 -100.0
  6      0   0   0    0   0   0   0    0  0.000  0.000  0.000  0.000 -100.0
  7      0   0   0    0   0   0   0    0    NaN    NaN    NaN    NaN    NaN
  8      0   0   0    0   0   0   0    0    NaN    NaN    NaN    NaN    NaN
  9      0   0   0    0   0   0   0    0  0.000  0.000  0.000  0.000 -100.0
  10     0   0   0    0   0   0   2    4  0.167  0.286  0.167  0.452   24.0
  11     0   0   0    0   0   0   0    0    NaN    NaN    NaN    NaN    NaN
  12     0   0   0    0   0   0   0    0    NaN    NaN    NaN    NaN    NaN
  13     0   0   0    1   0   0   0    4  0.091  0.091  0.091  0.182  -52.0
  14     2   0   0    9   1   1   2    4  0.347  0.389  0.388  0.777  107.0
  15     1   0   0    0   1   0   7   15  0.195  0.313  0.220  0.532   52.0
  16    13   5   3   32   8   2  19   47  0.264  0.312  0.367  0.679   77.0
  17    13   0   8   26   5   1  10   45  0.232  0.272  0.436  0.709   82.0
  18    27   3  15   84   7   4  29   77  0.293  0.325  0.433  0.758   98.0
  19     7   1   3   12  10   1   8   33  0.294  0.338  0.426  0.764  101.0
  20     6   0   1   10   2   1   9   27  0.210  0.255  0.275  0.530   41.0
  21     2   0   2    9   0   0   4   23  0.206  0.254  0.333  0.587   52.0
  22    21   2  25   71   2   1  42  100  0.264  0.337  0.506  0.843  120.0
  23     2   0   1    3   0   0   5   11  0.193  0.292  0.281  0.573   61.0
  24     0   0   0    0   0   0   0    0    NaN    NaN    NaN    NaN    NaN
...     ..  ..  ..  ...  ..  ..  ..  ...    ...    ...    ...    ...    ...
h 1589   0   0   0    0   0   0   0    0    NaN    NaN    NaN    NaN    NaN
  1590   0   0   0    0   0   0   0    0    NaN    NaN    NaN    NaN    NaN
  1591  28   4  11   61  15   8  36   95  0.262  0.321  0.386  0.707   93.0
  1592   2   0   0    4   0   0   4   34  0.164  0.220  0.200  0.420   19.0
  1595   0   0   0    2   0   0   2   16  0.100  0.156  0.100  0.256  -27.0
  1596   0   0   0    0   0   0   0    0  0.000  0.000  0.000  0.000 -100.0
  1597   1   0   0    0   0   0   0    6  0.176  0.176  0.235  0.412   13.0
  1598   7   0   5   17   2   1  22   36  0.289  0.379  0.434  0.814  128.0
  1599   0   0   0    0   0   0   0    1  0.500  0.500  0.500  1.000  176.0
  1600   0   0   0    0   0   0   0    0  0.000  0.000  0.000  0.000 -100.0
  1601   0   0   0    0   0   0   0    0    NaN    NaN    NaN    NaN    NaN
  1604   0   0   0    0   0   0   0    0    NaN    NaN    NaN    NaN    NaN
  1605  30   2   7   44  16   5  47  101  0.300  0.366  0.416  0.782  116.0
  1606   8   1   0    9   1   0   3   28  0.260  0.277  0.339  0.616   56.0
  1607  20   1  14   42   3   1  30   73  0.252  0.320  0.453  0.773  111.0
  1609   6   0   2   16   0   0   4   29  0.270  0.289  0.339  0.628   71.0
  1610   4   2   0    5   6   2   6   18  0.153  0.217  0.247  0.464   30.0
  1613   0   0   0    0   0   0   0    0    NaN    NaN    NaN    NaN    NaN
  1614  25   1  16   73   1   0  33   79  0.249  0.308  0.465  0.773  106.0
  1615   1   0   0    3   0   0   0   18  0.159  0.159  0.175  0.333  -10.0
  1616   0   0   0    0   0   0   0    0    NaN    NaN    NaN    NaN    NaN
  1617  36   3  13   56   3   4  62   56  0.276  0.359  0.450  0.809  120.0
  1620  11   0  11   28   0   1  21  132  0.174  0.230  0.300  0.530   49.0
  1621   0   0   0    0   0   0   0    0    NaN    NaN    NaN    NaN    NaN
  1622  27   3  16   64   8   3  46  123  0.253  0.316  0.403  0.719    NaN

         TB  GDP  HBP  SH  SF  IBB Pos Summary  year
a 0       0    0    0   0   0    0           1  2008
  1      28    0    2   1   1    0          78  2008
  2     287   14    1   0   1    2        *9/D  2008
  3       0    0    0   0   0    0           1  2008
  4       0    0    0   0   0    0          /1  2008
  5       0    0    0   0   0    0           1  2008
  6       0    0    0   0   0    0           1  2008
  7       0    0    0   0   0    0          /1  2008
  8       0    0    0   0   0    0          /1  2008
  9       0    0    0   0   0    0           1  2008
  10      2    1    0   1   0    0          /7  2008
  11      0    0    0   0   0    0          /1  2008
  12      0    0    0   0   0    0           1  2008
  13      1    2    0   0   0    0          /2  2008
  14     19    1    2   0   1    0         7/D  2008
  15      9    0    0   0   0    0         /98  2008
  16    114    6    3   4   0    1        8654  2008
  17     79    2    0   2   0    0       8/D79  2008
  18    241   11    1   0   6    6          7D  2008
  19     58    1    1   1   0    2      Aug-79  2008
  20     38    2    0   2   2    0       7/34D  2008
  21     21    1    0   1   0    0       4/658  2008
  22    209    8    5   0   3    3        87/9  2008
  23     16    1    3   0   0    1           4  2008
  24      0    0    0   0   0    0          /1  2008
...     ...  ...  ...  ..  ..  ...         ...   ...
h 1589    0    0    0   0   0    0          /1  2015
  1590    0    0    0   0   0    0          /1  2015
  1591  215   10   15   0   5    2          *4  2015
  1592   11    2    0   8   0    0           1  2015
  1595    3    0    0   0   0    0           1  2015
  1596    0    0    0   0   0    0          /1  2015
  1597    4    0    0   1   0    0           1  2015
  1598   66    4    0   0   0    0           5  2015
  1599    1    0    0   1   0    0           1  2015
  1600    0    0    0   1   0    0           1  2015
  1601    0    0    0   0   0    0           1  2015
  1604    0    0    0   0   0    0           1  2015
  1605  198   13    2   0   0    2         *78  2015
  1606   43    2    0   1   0    0       75/64  2015
  1607  144    6    3   3   2    2      *978/D  2015
  1609   59    8    1   0   1    0        9/D7  2015
  1610   21    1    1   2   0    1        78/9  2015
  1613    0    0    0   0   0    0           1  2015
  1614  161   13    1   0  10    0       7-Mar  2015
  1615   11    0    0   6   0    0           1  2015
  1616    0    0    0   0   0    0          /1  2015
  1617  210    8    1   0   5    3      47/D95  2015
  1620  105    6    5   8   2    0          *2  2015
  1621    0    0    0   0   0    0           1  2015
  1622  218   12    5   4   4    3         NaN  2015

[10335 rows x 31 columns]

In [200]:
bdf['Name'] = bdf.PLAYER.str.split('(').str.get(0)
bdf['Temp_Year'] = bdf.PLAYER.str.split('(').str.get(1)
bdf['First_Year'] = bdf.Temp_Year.str.split('-').str.get(0)
bdf['LYTemp'] = bdf.Temp_Year.str.split('-').str.get(1)
bdf['Last_Year'] = bdf.LYTemp.str.split(')').str.get(0)

pdf['Name'] = pdf.PLAYER.str.split('(').str.get(0)
pdf['Temp_Year'] = pdf.PLAYER.str.split('(').str.get(1)
pdf['First_Year'] = pdf.Temp_Year.str.split('-').str.get(0)
pdf['LYTemp'] = pdf.Temp_Year.str.split('-').str.get(1)
pdf['Last_Year'] = pdf.LYTemp.str.split(')').str.get(0)

In [206]:
bdf['Contract_Year'] = bdf['First_Year'].astype('int')
bdf['Contract_Year'] = bdf['Contract_Year'] -1

pdf['Contract_Year'] = pdf['First_Year'].astype('int')
pdf['Contract_Year'] = pdf['Contract_Year'] -1

#player_contracts.count()
#bdf.count() + pdf.count()

In [187]:
contract_stats = []

for player in bdf:
    if bdf['Name'] == batting['Name'] and bdf['Contract_Year'] == batting['year']:
        dfc = pd.concat([bdf, batting])

ValueError: Series lengths must match to compare